server:
  port: 0
  error:
    include-stacktrace: never
# [SWAGGER-INI] 
# Configuración de SpringDoc/Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# [SWAGGER-FIN] 

spring:
  application:
    name: ms-usuarios
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/usuarios
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.add.type.headers": false
# [JJWT-INI]
# ── Configuración JWT ──────────────────────────────────────────
# Esta clave secreta DEBE ser idéntica en todos los microservicios
# para que los tokens generados por ms-usuarios sean válidos en
# ms-catalogo y ms-recursos.
# Para dar el valor al "secret" trasformaremos la frase clave (inventada) 
# "tokenSecretKeySoftwareTienda2026PcHardwareSecurity" a formato Base64
jwt:
  secret: "dG9rZW5TZWNyZXRLZXlTb2Z0d2FyZVRpZW5kYTIwMjZQY0hhcmR3YXJlU2VjdXJpdHk="
  expiration-ms: 3600000   # 1 hora en milisegundos
# [JJWT-FIN]
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60
