docker exec -i postgres-db psql -U postgres -d postgres < 01-init.sql
docker exec -i postgres-db psql -U postgres -d postgres < 02-create_usuarios.sql
docker exec -i postgres-db psql -U postgres -d postgres < 03-create_catalogo.sql
docker exec -i postgres-db psql -U postgres -d postgres < 04-create_stock.sql
docker exec -i postgres-db psql -U postgres -d postgres < 05-create_pedidos.sql
docker exec -i postgres-db psql -U postgres -d postgres < 06-create_pagos.sql
docker exec -i postgres-db psql -U postgres -d postgres < 07-create_envios.sql
docker exec -i postgres-db psql -U postgres -d postgres < 08-create_tasacion.sql
docker exec -i postgres-db psql -U postgres -d postgres < 09-create_garantias.sql
docker exec -i postgres-db psql -U postgres -d postgres < 10-create_devoluciones.sql
docker exec -i postgres-db psql -U postgres -d postgres < 11-create_soporte.sql
docker exec -i postgres-db psql -U postgres -d postgres < 12-create_armado.sql
docker exec -i postgres-db psql -U postgres -d postgres < 13-create_notificaciones.sql